name: Docker debug

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker run -d nginx
        echo "run"
        docker ps -a
        docker ps -aq | while read list; do
          docker stop $list
          docker rm $list
        done
        echo "after stop"
        docker ps -a
        #docker ps -aq | xargs docker stop | xargs docker rm
        #echo "after rm"
        #docker ps -a
        #docker stop $(docker ps -a -q)
        #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
